Update for 1.18.2
TerraformersMC/Campanion pull request #163
Opened 2022-03-31 22:55 UTC by Jade-TheCat

I noticed that the current version does not work on 1.18.2 due to the changes to tags. I am also submitting a PR to Dossier for this same reason. Since FabricToolTags was removed, I have instead used the `c:shears` tag for that purpose.

2022-03-31 22:58 UTC, Jade-TheCat commented
PR for Dossier (required for this to work): https://github.com/TerraformersMC/Dossier/pull/3

2022-04-11 08:58 UTC, jhbuchanan45 approved these changes
@Jade-TheCat  Thanks for this and the changes to Dossier, I've been meaning to do it but been too busy to look at it until recently. 

Everything here also looks fine to me, I'll build it locally and have a quick test run later but can't see anything problematic. 

@NeusFear could you take a look at this and the linked Dossier changes when you get chance?

2022-04-20 16:40 UTC, NeusFear approved these changes
All looks good to me, once we get the changes we requested on dossier fixed we can re-run the tests and hopefully merge if all pass

2022-04-20 17:11 UTC, Wyn-Price requested changes
Most of this is just mappings changes. 
You seem to have missed the fabric shears tag at `net.fabricmc.fabric.api.tag.convention.v1.SHEARS`, and while what is currently done *would* work, there is no need to mirror it.

2022-04-20 17:11 UTC, Wyn-Price commented on src/main/java/com/terraformersmc/campanion/client/renderer/item/FakeWorld.java
> +import net.fabricmc.fabric.impl.registry.sync.FabricRegistry;
What's with all the import changes

2022-04-20 17:11 UTC, Wyn-Price commented on src/main/java/com/terraformersmc/campanion/recipe/TarpRecipe.java
> +			if(stack.isIn(CampanionItemTags.SHEARS)) {
We don't need our own shears tag. Please use `net.fabricmc.fabric.api.tag.convention.v1.SHEARS`

2022-04-20 17:11 UTC, Wyn-Price commented on src/main/java/com/terraformersmc/campanion/recipe/TarpRecipe.java
> +		list.add(Ingredient.fromTag(CampanionItemTags.SHEARS));
Again, use the fabric provided sheers tag

2022-04-20 17:11 UTC, Wyn-Price commented on src/main/java/com/terraformersmc/campanion/recipe/TarpRecipe.java
> +			ItemStack stack = inventory.getStack(i).copy();
Is there a reason for the copy here?

2022-04-20 17:11 UTC, Wyn-Price commented on src/main/java/com/terraformersmc/campanion/recipe/TarpRecipe.java
> +			if(stack.isIn(CampanionItemTags.SHEARS)) {
Please use the fabric provided shears tag

2022-04-20 17:11 UTC, Wyn-Price commented on src/main/java/com/terraformersmc/campanion/tag/CampanionItemTags.java
> +	public static final TagKey<Item> SHEARS = TagKey.of(Registry.ITEM_KEY, new Identifier("c", "shears"));
We don't need to mirror the fabric shears tag

2022-04-20 17:11 UTC, Wyn-Price commented on src/main/resources/data/c/tags/items/shears.json
> +{
Please use the fabric provided shears tag

2022-05-24 00:49 UTC, Jade-TheCat commented
Closing since a 1.18.2 update has already gone through! Thank yall

2022-05-24 00:49 UTC, closed without merging