Fix some block entities not rendering in tent preview
TerraformersMC/Campanion pull request #168
Opened 2022-04-25 12:58 UTC by jhbuchanan45

Block ID required in the nbt. Our block entity toTag() implementation mistakenly did this when the ID should only be added when the createNbtWithId() method is called.

Partially closes #167 
I have also extensively looked into the grass blocks not rendering. It turns out any block rendered on the CUTOUT_MIPPED layer has this issue, and it has to do with our TentPreviewBufferBuilder vertex method multiplying the alpha value. I have *no* idea why this matters, someone more knowledgeable in shaders and minecraft rendering may know.

2022-04-25 13:02 UTC, Wyn-Price commented
Do we still need `InvokerBlockEntity` now the call is removed?

I noticed that normal CUTOUT *does* work, while CUTOUT_MIPPED does not. I plan to dive into the shader code after work today

2022-04-25 13:02 UTC, Wyn-Price approved these changes

2022-04-25 13:06 UTC, Wyn-Price requested changes

2022-04-25 13:06 UTC, Wyn-Price commented on src/main/java/com/terraformersmc/campanion/blockentity/TentPartBlockEntity.java
> -		((InvokerBlockEntity) this).callWriteIdentifyingData(tag);
Could you remove the mixin as I don't believe we need it any longer

2022-04-26 19:17 UTC, Wyn-Price commented
A PR fixing `cutout_mipped` can be found here #169, once you remove that mixin, I'll merge and push a change to curseforge. Thanks for the help!

2022-04-26 19:21 UTC, jhbuchanan45 commented
> A PR fixing `cutout_mipped` can be found here #169, once you remove that mixin, I'll merge and push a change to curseforge. Thanks for the help!

Great, this PR should be ready now

2022-04-26 19:26 UTC, Wyn-Price approved these changes

2022-04-26 19:27 UTC, merged